language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required

addons:
  homebrew:
    packages:
    - glpk

  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libglpk-dev
    - glpk-utils
    - libboost-all-dev

script:
  - make test