language: cpp
jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
  - os: osx
    osx_image: xcode10.3
    compiler: clang

cache:
  directories:
    - ./benchmarks

addons:
  homebrew:
    packages:
    - glpk
    update: true
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libglpk-dev
    - glpk-utils
    - libboost-all-dev

script:
  - pip install psutil pandas matplotlib --user 
  - make sdf3_benchmarks
  - CTEST_OUTPUT_ON_FAILURE=1 make unit_test
  - make test
