language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libglpk-dev
    - glpk-utils
    - libboost-all-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install glpk    ; fi

script:
  - make test