language: cpp

os:
  - linux
  - osx

dist: bionic
osx_image: xcode10.3

compiler:
  - gcc
  - clang

cache:
  directories:
    - ./benchmarks
    - ./tools/sdf3*/
     
addons:
  homebrew:
    packages:
    - glpk
    update: true
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libglpk-dev
    - glpk-utils
    - libboost-all-dev

script:
  - ./tools/install_sdf3.sh
  - make sdf3_benchmarks
  - make unit_test
  - make test